<a href="https://colab.research.google.com/github/sonujangid1402/sonu-jangid/blob/main/predict_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import sklearn as sk
home=[1000,2000,3000,4000,5000,6000,7000,8000,9000,10000]
price=[100,200,300,400,500,600,700,800,900,1000]
x=np.array(home)
y=np.array(price)
print(arr)
print(type(arr))

[ 100  200  300  400  500  600  700  800  900 1000]
<class 'numpy.ndarray'>


In [5]:
# import packages
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split
home = np.array([1000,2000,3000,4000,5000,6000,7000,8000,9000,10000])
price = np.array([100,200,300,400,500,600,700,800,900,1000])
print(home)
print(price)


home_train,home_test,price_train,price_test = train_test_split(
    home,price,random_state=41,test_size=0.5,shuffle=True)
print("home_train:",home_train)
print("home_test:",home_test)
print("price_train:",price_train)
print("price_test:",price_test)


[ 1000  2000  3000  4000  5000  6000  7000  8000  9000 10000]
[ 100  200  300  400  500  600  700  800  900 1000]
home_train: [10000  3000  5000  4000  1000]
home_test: [6000 7000 8000 9000 2000]
price_train: [1000  300  500  400  100]
price_test: [600 700 800 900 200]


In [12]:
# import packages
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
home = np.array([1000,2000,3000,4000,5000])
price = np.array([100,200,300,400,500])
print(home)
print(price)


home_train,home_test,price_train,price_test = train_test_split(
    home,price,random_state=41,test_size=0.5,shuffle=True)
print("home_train:",home_train)
print("home_test:",home_test)
print("price_train:",price_train)
print("price_test:",price_test)
home_train =home_train.reshape(-1,1)
home_test = home_test.reshape(-1,1)
price_train=price_train.reshape(-1,1)
price_test=price_test.reshape(-1,1)
regr = LinearRegression()

regr.fit(home_train.reshape(-1,1),price_train.reshape(-1,1))
print(regr.score(home_test.reshape(-1,1),price_test.reshape(-1,1)))
print(regr.predict(home_test.reshape(-1,1)))

[1000 2000 3000 4000 5000]
[100 200 300 400 500]
home_train: [4000 1000]
home_test: [2000 3000 5000]
price_train: [400 100]
price_test: [200 300 500]
1.0
[[200.]
 [300.]
 [500.]]
